### ISSUE TITLE
Synchronisation between TeXlipse editor and external viewer does not work

### ISSUE THREAD

**Issue by bugybunny** [eclipse/texlipse#44]
At least I believe, I have minimal knowledge about native methods. I write down how I discovered that, so maybe someone can point out that this error is something completely different and can give me a solution :D
I have been using [this tutorial](https://joerglenhard.wordpress.com/2011/12/29/texlipse-and-sumatrapdf/) for years to configure inverse search support for SumatraPDF. With the 2.0.0 release it’s not working anymore.

I send the command `javaw -classpath [...]\.p2\pool\plugins\org.eclipse.texlipse_2.0.0.201709271122.jar" org.eclipse.texlipse.viewer.util.FileLocationClient -p 55000 -f %f -l %l` from Sumatra when double clicking to start the inverse search and have the focus set to Eclipse and jump to the line that defines the double clicked text. Inverse search support port number is left at its default `55000`.
Whenever I double click and the command is sent, Eclipse shows an error dialog and the error log shows `An internal error occurred during: "Launching Preview Document in sumatra PDF".` with the stacktrace.

```
java.lang.UnsatisfiedLinkError: org.eclipse.texlipse.DDEClient.execute(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
	at org.eclipse.texlipse.DDEClient.execute(Native Method)
	at org.eclipse.texlipse.viewer.ViewerManager.sendDDEViewCommand(ViewerManager.java:392)
	at org.eclipse.texlipse.viewer.ViewerManager.preview(ViewerManager.java:147)
	at org.eclipse.texlipse.viewer.TexLaunchConfigurationDelegate.launch(TexLaunchConfigurationDelegate.java:68)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

```

So I looked at DDEClient.execute, saw what library it was loading (I have a 64bit Win10 and `System.getProperty("os.arch")` returns `amd64` so `ddeclient-x86_64` is loaded. I thought maybe the DLL cannot be loaded so I moved it to a folder that is included in my PATH variable but that resulted in the same error. 
Then I examined the DLL with a tool that shows the exported functions and found that the function is still named with the old package naming net.sourceforge.texlipse.
![image](https://user-images.githubusercontent.com/5311105/32136100-c74fc682-bc09-11e7-80bb-8f8498d650d5.png)

I guess that’s the problem, right? If not, I would love to have a hint. Until then I’m going back to the 1.5.0 release with net.sourceforge.texlipse package naming because I cannot work productively without this feature. 

Oh, and don’t forget to also rename the 32 Bit DLL function name :)

**Comment by turesheim** [comment]
Thanks for the detailed report. It will certainly help fixing the issue.

**Comment by turesheim** [comment]
So we have two separate, but related, issues here:
* Synchronization from TeXlipse to SumatraPDF does not work (DLL)
* Synchronization from SumatraPDF to TeXlipse does not work (socket)

**Comment by turesheim** [comment]
It looks good now. Please give it a spin by installing from https://ci.eclipse.org/texlipse/job/continuous/ws/org.eclipse.texlipse_site/target/repository/

**Comment by bugybunny** [comment]
I installed from https://ci.eclipse.org/texlipse/job/continuous/ws/org.eclipse.texlipse_site/target/repository/ (org.eclipse.texlipse_2.0.0.201707291955.jar) and now I also get the error on the forward search (when pressing Ctrl+4 to open the created PDF in sumatra). Error is the same again

```
java.lang.UnsatisfiedLinkError: org.eclipse.texlipse.DDEClient.execute(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
	at org.eclipse.texlipse.DDEClient.execute(Native Method)
	at org.eclipse.texlipse.viewer.ViewerManager.sendDDEViewCommand(ViewerManager.java:392)
	at org.eclipse.texlipse.viewer.ViewerManager.preview(ViewerManager.java:147)
	at org.eclipse.texlipse.viewer.TexLaunchConfigurationDelegate.launch(TexLaunchConfigurationDelegate.java:68)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

```

I had a look at the delivered DLL again and the signature is still Java_net_sourceforge_… Should this be?
I saw in your commit that you added a readme on how to build the DLLs. I do not have to do this by myself, do I? Otherwise I wouldn’t understand why they are still delivered.

**Comment by bugybunny** [comment]
Accidentally clicked on close and comment instead of comment. Is not closed yet.

**Comment by turesheim** [comment]
Well, I can only assume that something went wrong on the CI-service, as the binaries I have in my test environment works just fine. I'll get back to you once I have made certain. My apologies for the trouble.

**Comment by bugybunny** [comment]
Works for me now, thanks!

If anyone else stumbles upon this via a Google search: The inverse command to set in Sumatra is 
`javaw -classpath "%homepath%\.p2\pool\plugins\org.eclipse.texlipse_2.0.1.201710312045\texlipse.jar" org.eclipse.texlipse.viewer.util.FileLocationClient -p 55000 -f "%f" -l %l` if you have an Eclipse OOMPH installation and your .p2 repo is in the home directory. You have to change the texlipse version, rest should be good if you left the default port number in the texlipse settings.

**Comment by LeonardMichlmayr** [comment]
I just tried the command with texlipse 2.0.1.201801202105, but it failed with the error message: Couldn't get I/O for the connection to: localhost

What can I try to find out more?

**Comment by bergmanngabor** [comment]
Forward search works fine, but inverse search seems to be a NO-OP in current snapshot version. To try to debug the issue I tried manually executing the following command line from CMD.EXE:

```
javaw -classpath $my-bundle-pool-location$\pool\plugins\org.eclipse.texlipse_2.0.2.201807240750\texlipse.jar net.sourceforge.texlipse.viewer.util.FileLocationClient -p 55000 -f "$my-texlipse-project-location$\intro.tex" -l 32
```

But nothing at all happened. Am I missing something?
