### ISSUE TITLE
Remove --src-specials from xelatex default arguments as it is not supported

### ISSUE THREAD

**Issue by bugybunny** [eclipse/texlipse#47]
https://github.com/eclipse/texlipse/blob/dd800ed5d181fbac75be483935cd063ec7808242/org.eclipse.texlipse/source/org/eclipse/texlipse/builder/XelatexRunner.java#L45

`XelatexRunner#getDefaultArguments()` inherits the default argument from https://github.com/eclipse/texlipse/blob/dd800ed5d181fbac75be483935cd063ec7808242/org.eclipse.texlipse/source/org/eclipse/texlipse/builder/LatexRunner.java#L63. `--src-specials` results in following error when running something like `xelatex.exe -synctex=1 -interaction=nonstopmode --src-specials index.tex `

```
ERROR xelatex.core - MiKTeX encountered an internal error.
ERROR xelatex.core - Data: 
ERROR xelatex.core - Source: libraries\miktex\texandfriends\include\miktex\texandfriends\StringHandlerImpl.h:47
…
INFO  xelatex - finishing with exit code 1
```
At least with MikTeX on Windows, guess it is also the case with other distributions. 
I googled because I had this issue and found someone else that had the exact same problem https://tex.stackexchange.com/questions/398779/miktex-2-9-internal-error-stringhandlerimpl-h.

Can someone else also confirm that `--src-special` is problematic? I don’t have enough knowledge to know what it actually means. MikTeX doc says 
> --src-special
> Embed source file information (source specials) in the DVI file.

Does this mean, it should only be passed when generating a dvi but not a pdf?

**Comment by swaldman3** [comment]
I'm no expert, but I think the same is true with the current version of LuaTeX in MikTeX's distro; that switch produces an error. I also don't really understand what source specials do in PDFs as opposed to DVIs, but I've had no ill effects from removing that switch from the LuaTeX command line.

**Comment by turesheim** [comment]
I have to trust you on this. I have seen no adverse effects removing the argument and testing using TeX Live on macOS. A build is coming right up if you want to try it out.
