### ISSUE TITLE
Set up Tycho building

### ISSUE THREAD

**Issue by turesheim** [eclipse/texlipse#6]

**Comment by jarrah42** [comment]
Should we get a hudson instance set up for texlipse?

**Comment by turesheim** [comment]
I was thinking Travis-CI would be just fine for our needs. If that doesn't work out we could get a JIPP instance. I believe Hudson is being phased out.

**Comment by jarrah42** [comment]
Can you sign plugins with Travis-CI? I wasn't aware Hudson was being phased out.

**Comment by turesheim** [comment]
Good point. I don't know if we can get signing to work with Travis-CI. With regards to Hudson I think I saw an e-mail encouraging new projects to use Jenkins. Hudson has not had any commits for at least a year.

**Comment by jarrah42** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=519434
