### ISSUE TITLE
Texlipse preferences crash in Eclipse Photon Release (4.8.0)

### ISSUE THREAD

**Issue by ykazakov** [eclipse/texlipse#61]
## Bug report

**What is the current behavior?**

Opening 
Preferences > Texlipse > Builder Settings 
as well as
Preferences > Texlipse > Viewer Settings 
result in a popup message:
"The currently displayed page contains invalid values"

Configuring texlipse is thus not possible.

**What is the expected or desired behavior?**

Preferences should be displayed in wich it is possible to set paths to latex / viewer commands

**Please provide steps to reproduce:**

* Install Eclipse Photon Release (4.8.0)
* Install texlipse 2.0.1 from Eclipse Marketplace
* Restart Eclipse as required
* Open Preferences > Texlipse > Builder Settings 

**Please describe your environment:**

* TeXlipse version: 2.0.1
* Eclipse version: 4.8.0

Operating system:
- [ ] Windows
- [x] macOS
- [ ] Linux

**Further details:**
The problem is probably caused by the crash:
```
Exception:java.lang.NoClassDefFoundError: org/eclipse/ui/help/WorkbenchHelp
	 at org.eclipse.texlipse.properties.ViewerSettingsPreferencePage.createFieldEditors(ViewerSettingsPreferencePage.java:52)
...
```
and
```
Exception:java.lang.NoClassDefFoundError: org/eclipse/ui/help/WorkbenchHelp
	 at org.eclipse.texlipse.properties.BuilderSettingsPreferencePage.addBuilderList(BuilderSettingsPreferencePage.java:185)
```

The likely reason is [the removal of deprecated APIs from Eclipse 4.8.0](http://help.eclipse.org/photon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fporting%2Fremovals.html&resultof=%22%6f%72%67%2f%65%63%6c%69%70%73%65%2f%75%69%2f%68%65%6c%70%2f%57%6f%72%6b%62%65%6e%63%68%48%65%6c%70%22%20&anchor=icontextcomputer).

**Comment by mrakitin** [comment]
I observe the same issue with the latest Eclipse.

**Comment by bergmanngabor** [comment]
The same in Windows.

**Comment by heruan** [comment]
I confirm this. Plus: I can't find TeXlipse wizard via File > New > Project… nor via File > Import…

**Comment by turesheim** [comment]
Thanks for the detailed bug report! Please try the build at https://ci.eclipse.org/texlipse/job/continuous/ws/org.eclipse.texlipse-site/target/repository/ – I'll prepare a new release as soon as possible.

**Comment by mrakitin** [comment]
Thanks for the fix! Looking forward for v2.0.2.

**Comment by turesheim** [comment]
I think I'll be able to get it out before Friday. The marketplace entry has been updated to indicate that the 2.0.1 version does not work with Eclipse Photon https://marketplace.eclipse.org/content/eclipse-texlipse

**Comment by ykazakov** [comment]
Tested, works now. Thanks for the quick fix!
