### ISSUE TITLE
Set up continuous building with Jenkins-CI

### ISSUE THREAD

**Issue by turesheim** [eclipse/texlipse#7]
This should probably be deferred until we get the Science TLP key.

**Comment by turesheim** [comment]
See #6 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=519434

**Comment by turesheim** [comment]
We now have an instance at https://ci.eclipse.org/texlipse/ – next up to add required plugins and triggers so that we can have automatic builds per pull request and merge.

**Comment by jarrah42** [comment]
I tried a build just to see what would happen :-)

**Comment by turesheim** [comment]
Jazzy is missing – I'll have a go at fixing it.

**Comment by turesheim** [comment]
Looks good now.

**Comment by turesheim** [comment]
Jenkins is building every 30 minutes regardless of whether there have been any changes to the source code. This will hopefully be fixed once we get the correct plug-ins installed and configured.

**Comment by jarrah42** [comment]
I think this is because the refspec is '*/master' and there is a branch called 'refs/heads/_old/master'. The git ls-remote command returns this in addition to the 'refs/heads/master' branch and is using the wrong revision id to compare to the latest build. I think if these old branches were removed it would work, or alternatively specify 'refs/heads/master' in the configuration.

**Comment by turesheim** [comment]
Thanks for investigating Greg. I was wondering whether or not we should remove these old branches. There might be some reason to conserve these, I don't see any, otherwise we should just delete them. Please vote.

**Comment by turesheim** [comment]
It looks fairly good now. Builds are executed every five minutes whenever there is a pull request change. A link to the build is created in the pull request (as a check). Since we don't have any tests we don't really have to wait for the build to complete successfully. We'll revisit once we have something in place.
