### ISSUE TITLE
Wrong warnings with \href command

### ISSUE THREAD

**Issue by heruan** [eclipse/texlipse#73]
## Bug report

**What is the current behavior?**

Using `\href{https://github.com}{GitHub}`-like commands, TeXlipse issues a warning:

```
Key https://github.com is undefined
```

**What is the expected or desired behavior?**

No warning is issued.

**Please provide steps to reproduce:**

Place an `\href` command in the document.

**Please describe your environment:**

* TeXlipse version: 2.0.2.201807241928
* Eclipse version: 2019-06 (4.12.0)

Operating system:
- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by turesheim** [comment]
The _latex3.sablecc_ grammar contains the following code which will effectively treat anything ending with "ref" as a reference:
```
//supporting \eqref, \vref, etc.
    {normal->comcapt, comcapt} cref = '\' letter* 'ref';
```
