### ISSUE TITLE
Bibtex editor not working in Eclipe 2020-09

### ISSUE THREAD

**Issue by montex** [eclipse/texlipse#86]
After updating Eclipse to latest version (2020-09), the .bib editor does not work anymore. It simply will not show anything.

**Comment by LorenzoBettini** [comment]
@turesheim since this is a blocking issue, which seems to have been resolved, could we have a 2.0.3 released, please?
thanks in advance
Lorenzo

**Comment by turesheim** [comment]
Hi Lorenzo. Yes, I'll release a new build as soon as I can. Currently there is an issue with the Jenkins-GitHub integration which prevents CI. I'm waiting for the Eclipse team to remedy that.

**Comment by LorenzoBettini** [comment]
OK, thanks!

**Comment by montex** [comment]
@turesheim When facing a similar problem, I found that the bast way to integrate external non-eclipse library was to download them using maven, please check pull request #95, I think it may solve the problem.

**Comment by turesheim** [comment]
Thanks @montex, actually – the build issue was related to Jenkins CI being moved to new infrastructure and some parts not working as before. However PR #95 is definitely helpful so I've merged that. Closing this as the fix has been merged.
